default:
  before_script:
    - Chcp 65001
    - $env:Path = "C:/bin;" + $env:Path
    - $env:Path = "C:/Program Files/Git/cmd/;" + $env:Path
    - busybox date "+%Y.%m.%d.%H.%M.%S"
    - busybox pwd
    - $Env:_MSPDBSRV_ENDPOINT_="$Env:CI_JOB_ID"
    - Dir "Env:"
    - busybox time git submodule init
    - busybox time git submodule update --init --recursive

# ステージの定義 すべてのジョブはここで定義したステージのいずれかに属する 定義順にジョブが実行される
stages:
  - build

# このyml上で使う変数の定義
variables:
  GIT_SUBMODULE_STRATEGY: recursive

build_luajit:
  stage: build
  script:
    - echo build_luajit
    - echo $Env:CI_COMMIT_SHA
    - 'cmd.exe /c call "run.bat"'
    - echo finished.
    - echo zip all artifacts...

  artifacts:
    name: '$Env:CI_PROJECT_PATH_SLUG-$Env:CI_BUILD_REF_SLUG-$Env:CI_JOB_ID'
    paths:
      - "Build/*"

